title: "Balmung's Devlog"
author: "Octavio Navarro"
description: "A place to document things I learn or find interesting."

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
# email: "example@mail.com"
# twitter_username: "twitteruser"
github_username: "octavio-navarro"
linkedin_username: "octavio-navarro-hinojosa"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

minima:
  skin: dark

# sass:
#   sass_dir: _sass
#   style: dark-theme

# rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

home_post_limit: 5

titles_from_headings:
  strip_title: true
  collections: true

header_pages:
  - html/resume.html
  - html/repos.html
  - html/archive.html

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
